theme: jekyll-theme-minimal
title: Welcome to Alex Pickering's homepage
description: This is a digital playground for me to think deliberately, move quickly, and break things (hopefully more of the first two than the last one)

